name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 15
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: npm i
        env:
          CI: true

      - name: Lint
        run: npm run lint
        env:
          CI: true

      - name: Test
        run: npm test
        env:
          CI: true

      - name: Build
        run: npm run build
        env:
          CI: true
