on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  workflow:
    runs-on: ubuntu-latest
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: '24'
          cache: true

      - name: setup config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Install dependencies
        run: vp i

      - name: Lint
        run: vpr lint

      - name: Test
        run: vpr test

      - name: Type check
        run: vpr typecheck

      - name: Release
        run: vpr release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build website
        run: vpr build:web

      - name: Upload website artefacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist-website/'

      - name: Deploy website
        uses: actions/deploy-pages@v4
