name: Workflow

on: [push]

env:
  HUSKY: 0

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  doctor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Type check
        run: npm run typecheck -w tings

  release:
    if: github.ref == 'refs/heads/main'
    needs: [doctor]
    runs-on: ubuntu-latest
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Create release pull request or publish to npm
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: npm run build

      - name: Upload website artefacts
        if: steps.changesets.outputs.hasChangesets == 'false'
        uses: actions/upload-pages-artifact@v2
        with:
          path: './website/dist/'

      - name: Deploy website
        if: steps.changesets.outputs.hasChangesets == 'false'
        uses: actions/deploy-pages@v2
